global using System;
global using System.Collections.Generic;
global using FluentAssertions;
global using FluentAssertions.Extensions;
global using Microsoft.Extensions.DependencyInjection;
global using NSubstitute;
global using NSubstitute.ClearExtensions;
global using NSubstitute.ExceptionExtensions;
global using Xunit;
