name: '.NET'
description: 'Installs .NET deps'

runs:
  using: 'composite'
  steps:
    - name: Set Global Environment Variables
      shell: bash
      run: |
        echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
        echo "DOTNET_NOLOGO=1" >> $GITHUB_ENV

    # Note, the following is needed on the windows-2019 image only.
    # All other versions of .NET we need are pre-installed on the GitHub Actions virtual images.
    - name: Install .NET 6 SDK
      uses: actions/setup-dotnet@v3
      if: runner.os == 'Windows'
      with:
        dotnet-version: 6.x.x

    - name: Dependency Caching
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
