name: '.NET'
description: 'Installs .NET deps'

runs:
  using: 'composite'
  steps:
    - name: Set Global Environment Variables
      shell: bash
      run: |
        echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
        echo "DOTNET_NOLOGO=1" >> $GITHUB_ENV

    - name: Install .NET 6 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.428
      env:
        # https://github.com/dotnet/sdk/issues/44957
        DOTNET_INSTALL_DIR: ${{ runner.temp }}/.dotnet

    - name: Dependency Caching
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
