name: Automated deploy

on:
  release:
    types: [created]

env:
  TARGET_REF: ${{ github.event.release.target_commitish }}
  TAG: ${{ github.event.release.target_commitish == 'master' && 'latest' || 'next' }}

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.TARGET_REF }}
          token: ${{ secrets.GPR_TOKEN }}

      - name: Install deps
        uses: ./.github/workflows/composite/net

  publish:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.TARGET_REF }}
          token: ${{ secrets.GPR_TOKEN }}

      - name: Install deps
        uses: ./.github/workflows/composite/net

      - name: Restore .NET Dependencies
        run: dotnet restore --nologo --locked-mode

      - name: Build
        run: dotnet build -c Release --no-restore --nologo /p:CopyLocalLockFileAssemblies=true

      - name: Create Nuget Packages
        run: dotnet pack -c Release --no-build --nologo

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            src/**/bin/Release/*.nupkg

      - name: Publish package to NuGet
        run: dotnet nuget push src/**/bin/Release/*.nupkg -s nuget -k ${{ secrets.NUGET_TOKEN }}
